### ISSUE TITLE
Listen keyboard

### ISSUE THREAD

**Issue by gkhanacer** [Skycoder42/QHotkey#1]
Hi,

I'm trying to develop a keylogger with QHotkey for all platforms. So, I want to listen keyboard without signal/slot (connect). How can I use your code to listen system-wide keyboard?

**Comment by Skycoder42** [comment]
Hi,

I'm sorry to tell you, but thats impossible with QHotkey, it's not designed for that. QHotkey uses native APIs to register single keys as hotkey. For a keylogger, you will have to use native api hooks, and thats a completly different thing.
