### ISSUE TITLE
Failed to register hotkey on Ubuntu

### ISSUE THREAD

**Issue by pi-null-mezon** [Skycoder42/QHotkey#16]
Hello! When I am try to run library on ubuntu I have got:

````
$ sudo ./myapp
libEGL warning: DRI2: failed to authenticate
QHotkey: Failed to register hotkey. Error: BadAccess (attempt to access private resource denied)
...
````

and of cource hotkeys do not work after that. Maybe youalready have faced with that and can recommend what to do? Thanks! Great library by the way!

**Comment by Skycoder42** [comment]
This error typically means that you are trying to register a key X11 does not allow you to register. What key combination are you trying to register?

**Comment by pi-null-mezon** [comment]
Thank a lot! You are right, it was **Alt+P** that not worked.
