### ISSUE TITLE
Release a new version in qpm

### ISSUE THREAD

**Issue by semanser** [Skycoder42/QHotkey#19]
I have recently installed QHotkey from qpm, but looks like qpm use the outdated version of package and it should be updated. 
Also not sure why on Github the latest version is **1.1.3**, but on qpm - **1.2.1**.

**Comment by Skycoder42** [comment]
I had some issues with tags not beeing pushed when switching my VCS frontend - thats the reason for the version missmatch. I will update the qpm package right away

**Comment by Skycoder42** [comment]
Apparently tags have been pushed. I simply did not create a new release for the pushed tags
