### ISSUE TITLE
Cannot install on Windows via qpm

### ISSUE THREAD

**Issue by semanser** [Skycoder42/QHotkey#20]
Hey, I get next error when try to install this package via qpm:

```
INFO: Package de.skycoder42.qhotkey has a different license (BSD_3_CLAUSE) than it's dependant (NONE).
Installing de.skycoder42.qhotkey@1.2.2
QPM: 2018/04/11 15:00:50 ERROR: GetFileAttributesEx D:\Andriy\Programing\VT\visualtranslator\src\vendor\Skycoder42-QHotkey-547cf7a\doc\qpm.json: The system cannot find the file specified.
```

**Comment by Skycoder42** [comment]
Did you follow the hint in the readme for windows users?

> **Important for Windows users:** QPM Version *0.10.0* (the one you can download on the website) is currently broken on windows! It's already fixed in master, but not released yet. Until a newer versions gets released, you can download the latest dev build from here:
> - https://storage.googleapis.com/www.qpm.io/download/latest/windows_amd64/qpm.exe
> - https://storage.googleapis.com/www.qpm.io/download/latest/windows_386/qpm.exe

**Comment by semanser** [comment]
Thanks!
