### ISSUE TITLE
Add the ability to check if the platform is supported

### ISSUE THREAD

**Issue by Shatur95** [Skycoder42/QHotkey#27]
Thanks for your awesome library!
I have a suggestion. Since hotkeys for Linux work only for X11, then could you add a function that checks if the platform is supported? This can be convenient if I want to show the user in the UI that hotkeys cannot be registered.
This can be implemented by adding a function that returns true for Windows and Mac, and [QX11Info::isPlatformX11()](https://doc.qt.io/qt-5/qx11info.html#isPlatformX11) on Linux.
I can make a PR if you approve my suggestion.

**Comment by Skycoder42** [comment]
Sounds good to me. PRs are always welcome, so please, go ahead and create one!
