### ISSUE TITLE
Registering before creating the first window does not work

### ISSUE THREAD

**Issue by ArsenArsen** [Skycoder42/QHotkey#3]
Hello!
Using a hotkey before **showing** a `MainWindow` makes the QHotkey signals not trigger. Current workaround I've found is 
```cpp
    QApplication a(argc, argv);

    QCommandLineParser parser;
    parser.addHelpOption();

    QCommandLineOption h({ "b", "background" }, "Does not show the main window, starts in tray.");
    parser.addOption(h);
    parser.process(a);

    MainWindow w;
    w.show();
    QTimer::singleShot(0, [&] {
        if (parser.isSet(h)) w.hide();
    });
    return a.exec();
```
Which flashes the window for one event loop iteration (too short to be visible).

I assume this is a singleton not being set up issue.

The hotkeys are registered at the end of the `MainWindow` constructor.

Thanks for creating QHotkey! :)

**Comment by Skycoder42** [comment]
Well thats a surprise. This is definitly something that should work...Wich OS are you on (please detailed, e.g. Windows 10 Creators Update)? Am I assuming correctly that your non-workaround implementation looked like this:

```
MainWindow w;
if (!parser.isSet(h))
    w.show();
return a.exec();
```

**Comment by ArsenArsen** [comment]
Correct. I am using Arch Linux, with Xorg and KDE Plasma 5.
![](http://i.imgur.com/FbxwslZ.png)

**Comment by Skycoder42** [comment]
A fellow Arch/KDE user! I could verify the issue. There is probably something that needs to be activated by Qt, and this only happens on the first window show. I looked around, but couldn't find anything... The registration seems to work, but the key is not grabbed. (I tested with <key>S</key>).

For now, this workaround seems to work:
```
//In main
auto tmp = new QWidget();
tmp->show();
tmp->close();
tmp->deleteLater();
```

But I will try to find a proper solution. If not, I will integrate this code into the X11 implementation.

**Comment by Skycoder42** [comment]
Solution found! A missing call to `XSync`

**Comment by Skycoder42** [comment]
Please check if it works for you, and close the issue

**Comment by ArsenArsen** [comment]
Thanks! I won't be home 'till 9PM UK so won't be able to test.

Od: Felix Barz
Poslato: недеља 14. мај 13.32
Tema: Re: [Skycoder42/QHotkey] Registering before creating the first window does not work (#3)
Za: Skycoder42/QHotkey
Cc: ArsenArsen, Author


Please check if it works for you, and close the issue

**Comment by ArsenArsen** [comment]
👌
