### ISSUE TITLE
Infinite loop (ending in a segmentation fault) upon BadAccess

### ISSUE THREAD

**Issue by ArsenArsen** [Skycoder42/QHotkey#4]
When a `BadAccess` failure occurs during registering shortcuts QHotkey will go into an infinite loop, spamming the console each iteration.

```
WARN: Failed to unregister hotkey. Error: BadAccess (attempt to access private resource denied)
```

This time I tested it seems to have crashed. Segmentation fault @ `qhotkey_x11.cpp:133` (The `XSync` line).
![](http://i.imgur.com/1n6B6pp.png)

Tried again, the SIGSEGV is reproducable.

**Comment by Skycoder42** [comment]
Which key did you try to register? I cannot test unless I am able to reproduce this myself.

**Comment by ArsenArsen** [comment]
Oh whoops. Sorry. It fails if a keybind is already registered. Does not matter which one.

**Comment by Skycoder42** [comment]
Bug confirmed, I was able to reproduce it. Working on a solution

**Comment by Skycoder42** [comment]
Okay, it's a simple copy paste error… Of course, trying to unregister when unregistering fails is a nogo.

**Comment by Skycoder42** [comment]
Apparently, the call to XSync has more sideeffects than expected. As soon as one registration fails, all subsequent ones will as well. In other words, XSync renders QHotkey unusable after the first fail.

Without using this, however, no errors are reported at all. I will keep this issue open, until I can find a way to report errors properly, but I will remove XSync to make it usable again

**Comment by ArsenArsen** [comment]
Seems to have been fixed. Thanks! One question stands though, how do we actually properly handle registration failures?

**Comment by ArsenArsen** [comment]
Actually, seems that `isRegistered()` keeps returning true, which would be wrong because the hotkey is not really registered.

**Comment by Skycoder42** [comment]
Just like I said, error detection is not working yet. Neither can I receive error messages, nor can I detect whether registerings works or not.

Right now, there is no way to detect errors. I will have to find out why it is not possible to register hotkeys after the first fail (if error reporting is enabled) and find a fix.

**Comment by ArsenArsen** [comment]
Ah, I see. Excuse me. I'll keep the issue open for future reference. Thanks!

**Comment by Skycoder42** [comment]
Apparently, it was just me not clearing the static error flag...
