### ISSUE TITLE
Port it to Qt6

### ISSUE THREAD

**Issue by hbtalha** [Skycoder42/QHotkey#49]
It would be great if it is ported to Qt6 since x11extras module has been deprecated and is no longer part of Qt.
The functionality of the module has been incorporated into other parts of Qt, or in some cases removed due to being obsolete or better suited as cross platform APIs.

For more details, see [QTBUG-93633](https://bugreports.qt.io/browse/QTBUG-93633) in the Qt issue tracker.

**Comment by Shatur** [comment]
Sure, but I think we should wait until 6.2 because some functionality will be available as part of the cross-platform API.

**Comment by annahowell** [comment]
@Shatur Any movement on this now that 6.2 beta is out? Thanks

**Comment by Shatur** [comment]
> @Shatur Any movement on this now that 6.2 beta is out? Thanks

No, I going to port it when 6.2 will be stable.
