### ISSUE TITLE
[!] Looking for a Maintainer

### ISSUE THREAD

**Issue by Skycoder42** [Skycoder42/QHotkey#50]
As things stand right now, I personally do not have the time anymore to maintain this repository. I will still answer to issue and review and accept PRs though.

Since Qt 6 was released, according to #49, some major changes will have to be done to the code base, which I cannot provide. Thus, I am currently looking for someone to take over the repository and maintain it. If anyone is interested, please contact me here and state your preferred communication channel for further steps.

Thanks to everyone who has contributed so far!

**Comment by Shatur** [comment]
Hey! I use your library in my application and will port it to Qt6. But at the moment Qt6 is incomplete and should be usable in 6.2. Will send a PR.

**Comment by Skycoder42** [comment]
@Shatur Thanks, that's great. Would you also be interested in becoming a Co-Maintainer? That would allow you to push code directly to this repo, accept PRs, etc.

**Comment by Shatur** [comment]
@Skycoder42 Yes, I would like to help.

**Comment by Skycoder42** [comment]
Done
