### ISSUE TITLE
About QKeySequence

### ISSUE THREAD

**Issue by wy-luke** [Skycoder42/QHotkey#68]
Great repo, thanks!

>Only single key/modifier combinations are possible. If using QKeySequence, only the first key+modifier of the sequence will be used.

Is there any chance that QKeySequence would be supported? I really need this function.

Thanks!

**Comment by Shatur** [comment]
It is supported. You jut can't user any sequence, some of them can't be mapped globally due to os limitations.

**Comment by wy-luke** [comment]
> It is supported. You jut can't user any sequence, some of them can't be mapped globally due to os limitations.

Sorry, what I mean is multi-key combinations, like `Ctrl + K, Ctrl + D` ? 

I tried `Ctrl + X + C` , only `Ctrl + X` works.

**Comment by Shatur** [comment]
Yes, you can't map `Ctrl + X + C`, it's a system limitation.

**Comment by wy-luke** [comment]
> Yes, you can't map `Ctrl + X + C`, it's a system limitation.

Ok, I get it!

Thanks a lot! 🦾
