### ISSUE TITLE
SIGSEGV: x11Interface is null

### ISSUE THREAD

**Issue by SkyD666** [Skycoder42/QHotkey#82]
Ubuntu 22.10
Qt 6.4

file: qhotkey_x11.cpp 

line 134:
`
const QNativeInterface::QX11Application *x11Interface = qGuiApp->nativeInterface<QNativeInterface::QX11Application>();
`

x11Interface is null

![screenshot](https://user-images.githubusercontent.com/32453770/216876242-a8a91d7f-1bc9-451f-ac2c-4b48a179c0fe.jpg)

**Comment by ManuelSchneid3r** [comment]
Are you on Wayland?

**Comment by SkyD666** [comment]
oh sorry i'm using wayland.

Also, x11Interface should check for null first.
(line 141 and line 135)

thank you!

**Comment by Shatur** [comment]
Closed by #98.
