### ISSUE TITLE
Lets get org.freedesktop.portal.GlobalShortcuts off the ground

### ISSUE THREAD

**Issue by ManuelSchneid3r** [Skycoder42/QHotkey#99]
Resources:

- [xdg-desktop-portal docs](https://flatpak.github.io/xdg-desktop-portal/docs/)

**Comment by ManuelSchneid3r** [comment]
https://github.com/QtCommunity/QHotkey/issues/1

**Comment by Cuperino** [comment]
Here's the discussion that lead to the [GlobalShortcuts portal](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.impl.portal.GlobalShortcuts.html) creation: https://github.com/flatpak/xdg-desktop-portal/issues/624

Copied from there, here are two app implementations done by Aleix Pol:
- KDE test app: https://invent.kde.org/libraries/xdg-portal-test-kde/-/merge_requests/6
- Mumble: https://github.com/mumble-voip/mumble/pull/5976

**Comment by Cuperino** [comment]
This issue is a duplicate of #89. Let's use that instead.
